export const DESTINATIONS = [
  "Tokyo, Japan",
  "Kyoto, Japan",
  "Bali, Indonesia",
  "Jakarta, Indonesia",
  "Paris, France",
  "Nice, France",
  "New York City, USA",
  "Los Angeles, USA",
  "San Francisco, USA",
  "Dubai, United Arab Emirates",
  "Abu Dhabi, United Arab Emirates",
  "London, United Kingdom",
  "Manchester, United Kingdom",
  "Rome, Italy",
  "Venice, Italy",
  "Bangkok, Thailand",
  "Phuket, Thailand",
  "Singapore, Singapore",
  "Hong Kong, China",
  "Shanghai, China",
  "Beijing, China",
  "Seoul, South Korea",
  "Sydney, Australia",
  "Melbourne, Australia",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Cape Town, South Africa",
  "Marrakech, Morocco",

  "Goa, India",
  "Kashmir, India",
  "Jaipur, India",
  "Manali, India",

  "Agra (Taj Mahal), India",
  "Cusco (Machu Picchu), Peru",
  "Petra (Wadi Musa), Jordan",
  "Rio de Janeiro (Christ the Redeemer), Brazil",
  "Rome (Colosseum), Italy",
  "Yucatán (Chichen Itza), Mexico",
  "Grand Canyon (Arizona), USA",
  "Niagara Falls (Ontario), Canada",
  "Victoria Falls (Livingstone), Zambia",
  "Reykjavik (Northern Lights), Iceland",
  "Cairns (Great Barrier Reef), Australia"
];